# Generated by Django 3.2.5 on 2021-07-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('location', models.TextField(max_length=200)),
                ('pic_icon', models.ImageField(upload_to=None)),
                ('sig_dish', models.TextField(max_length=200)),
                ('num_favs', models.IntegerField(default=0)),
            ],
        ),
    ]
