# Generated by Django 3.2.5 on 2021-07-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='num_favs',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
