# Generated by Django 3.2.5 on 2021-07-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_num_favs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='num_favs',
            field=models.IntegerField(default=0),
        ),
    ]
