# Generated by Django 3.2.1 on 2021-07-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfruser',
            name='bio',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='tfruser',
            name='picture',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
