# Generated by Django 3.2.5 on 2021-07-08 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210707_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfruser',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=0, related_name='my_favs', to=settings.AUTH_USER_MODEL),
        ),
    ]
